<?php
/**
 * @category   Test
 * @package    Test_Demo
 * @author     mohitvamja1991@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Test\Demo\Block;

use Magento\Framework\View\Element\Template\Context;
use Test\Demo\Model\DemoFactory;
/**
 * Demo List block
 */
class DemoListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Demo
     */
    protected $_demo;
    public function __construct(
        Context $context,
        DemoFactory $demo
    ) {
        $this->_demo = $demo;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Test Demo Module List Page'));
        
        if ($this->getDemoCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'test.demo.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getDemoCollection()
            );
            $this->setChild('pager', $pager);
            $this->getDemoCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getDemoCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $demo = $this->_demo->create();
        $collection = $demo->getCollection();
        $collection->addFieldToFilter('status','1');
        //$demo->setOrder('demo_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}