<?php
/**
 * @category   Test
 * @package    Test_Demo
 * @author     mohitvamja1991@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Test\Demo\Block;

use Magento\Framework\View\Element\Template\Context;
use Test\Demo\Model\DemoFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Demo View block
 */
class DemoView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Demo
     */
    protected $_demo;
    public function __construct(
        Context $context,
        DemoFactory $demo,
        FilterProvider $filterProvider
    ) {
        $this->_demo = $demo;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Test Demo Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $demo = $this->_demo->create();
        $singleData = $demo->load($id);
        if($singleData->getDemoId() || $singleData['demo_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}